name: Deploy Vue Docs
on:
  release:
    types: [published]
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main

    - name: install
      run: yarn bootstrap

    - name: build:docs
      run: yarn build:docs

    - name: deploy
      uses: genietim/ftp-action@releases/v4
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        localDir: "./packages/vue3/doc-dist"
        remoteDir: "docs"