name: Deploy website
on:
  release:
    types: [published]
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main

    - name: install
      run: yarn bootstrap

    - name: build:vue
      run: yarn build:vue

    # - name: deploy
    #   uses: peaceiris/actions-gh-pages@v2
    #   env:
    #     ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    #     PUBLISH_BRANCH: gh-pages
    #     PUBLISH_DIR: ./packages/site/assets
    #   with:
    #     emptyCommits: false
